# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname= "node#{i}"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"
      node.vm.provider "v" do |v|
        v.cpu = 2
        v.memory = 4096
      end
    end
  end
end
