server:
  port: 8080

web:
  security:
    excludeUrlPatterns: /metrics, /admin/test

spring:
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 1KB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB
logging:
  level:
    root: INFO
